DECLARE
	v_count NUMBER;
BEGIN
	SELECT COUNT(*)
	INTO v_count
	FROM user_tables
	WHERE table_name = 'DEPT';

	IF v_count = 0 THEN
		EXECUTE IMMEDIATE 'CREATE TABLE DEPT (
			DEPTNO NUMBER(2) CONSTRAINT PK_DEPT PRIMARY KEY,
			DNAME VARCHAR2(14),
			LOC VARCHAR2(13)
		)';
	END IF;
END;
/

MERGE INTO DEPT d
USING (SELECT 10 DEPTNO, 'ACCOUNTING' DNAME, 'NEW YORK' LOC FROM dual) s
ON (d.DEPTNO = s.DEPTNO)
WHEN MATCHED THEN
	UPDATE SET d.DNAME = s.DNAME, d.LOC = s.LOC
WHEN NOT MATCHED THEN
	INSERT (DEPTNO, DNAME, LOC)
	VALUES (s.DEPTNO, s.DNAME, s.LOC);

MERGE INTO DEPT d
USING (SELECT 20 DEPTNO, 'RESEARCH' DNAME, 'DALLAS' LOC FROM dual) s
ON (d.DEPTNO = s.DEPTNO)
WHEN MATCHED THEN
	UPDATE SET d.DNAME = s.DNAME, d.LOC = s.LOC
WHEN NOT MATCHED THEN
	INSERT (DEPTNO, DNAME, LOC)
	VALUES (s.DEPTNO, s.DNAME, s.LOC);

MERGE INTO DEPT d
USING (SELECT 30 DEPTNO, 'SALES' DNAME, 'CHICAGO' LOC FROM dual) s
ON (d.DEPTNO = s.DEPTNO)
WHEN MATCHED THEN
	UPDATE SET d.DNAME = s.DNAME, d.LOC = s.LOC
WHEN NOT MATCHED THEN
	INSERT (DEPTNO, DNAME, LOC)
	VALUES (s.DEPTNO, s.DNAME, s.LOC);

MERGE INTO DEPT d
USING (SELECT 40 DEPTNO, 'OPERATIONS' DNAME, 'BOSTON' LOC FROM dual) s
ON (d.DEPTNO = s.DEPTNO)
WHEN MATCHED THEN
	UPDATE SET d.DNAME = s.DNAME, d.LOC = s.LOC
WHEN NOT MATCHED THEN
	INSERT (DEPTNO, DNAME, LOC)
	VALUES (s.DEPTNO, s.DNAME, s.LOC);

COMMIT;
