spring.application.name=kosa_3_Security_jwt-1

server.port=8090

kr.or.kosa.secret-key=HS`{|T0vkYS2Q~?T2S9$WqYdrX>kP1{,b(OiZ-g_s_Gz1.{?t2Kz8PYu|a)V3;/z

#Oracle
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XEPDB1
spring.datasource.username=springuser
spring.datasource.password=1004
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# DB 컬럼 view_count, created_at 를 자바 필드 viewCount, createdAt 로 자동 매핑
mybatis.configuration.map-underscore-to-camel-case=true

