-- =====================================================================
-- Oracle 용 board 테이블 스크립트 (springuser 계정으로 1회 실행)
-- =====================================================================
CREATE TABLE board (
    id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title      VARCHAR2(200) NOT NULL,
    writer     VARCHAR2(50)  NOT NULL,   -- 화면 표시용 작성자 이름
    owner      VARCHAR2(50),             -- 작성 계정 username (수정/삭제 권한 판별)
    content    CLOB,
    view_count NUMBER        DEFAULT 0,
    created_at TIMESTAMP     DEFAULT SYSTIMESTAMP
);

-- 샘플 게시글 (보여주기용). owner 는 로그인 계정(admin/hong)
INSERT INTO board(title, writer, owner, content) VALUES('첫 번째 게시글입니다', '관리자', 'admin', '안녕하세요. 게시판 첫 글입니다.');
INSERT INTO board(title, writer, owner, content) VALUES('JWT 로그인 테스트', '홍길동', 'hong', '로그인 후 글쓰기가 됩니다.');
INSERT INTO board(title, writer, owner, content) VALUES('React + Spring Boot', '관리자', 'admin', '프론트와 백엔드가 연결되었습니다.');

COMMIT;

SELECT id, title, writer, owner, view_count, created_at FROM board ORDER BY id;

-- (이미 board 테이블이 있고 owner 컬럼만 없을 때)
-- ALTER TABLE board ADD (owner VARCHAR2(50));
-- UPDATE board SET owner = writer WHERE owner IS NULL;
-- COMMIT;
