-- =====================================================================
-- Oracle 용 user2 테이블 스크립트 (springuser 계정으로 1회 실행)
-- 서버(kosa_3_Security_jwt-1) 를 처음 켜기 전에 실행하세요.
-- 초기 계정(admin/hong)은 서버 시작 시 DataInitializer 가 자동으로 넣어줍니다.
-- =====================================================================

-- [A] 새로 만드는 경우 -----------------------------------------------
CREATE TABLE user2 (
    id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50)  UNIQUE NOT NULL,
    password VARCHAR2(255)        NOT NULL,
    name     VARCHAR2(50)         NOT NULL,   -- 이번에 추가된 컬럼
    role     VARCHAR2(20)         NOT NULL
);

-- [B] 이미 user2 테이블이 있고 name 컬럼만 없는 경우 -----------------
--   (위 [A] 대신 아래 두 줄을 실행)
-- ALTER TABLE user2 ADD (name VARCHAR2(50));
-- UPDATE user2 SET name = username WHERE name IS NULL;   -- 기존 행 임시 채우기
-- ALTER TABLE user2 MODIFY (name VARCHAR2(50) NOT NULL);

COMMIT;

-- 확인
SELECT id, username, name, role FROM user2;
