package kr.or.kosa.domain;

import java.time.LocalDateTime;

import lombok.Data;

/*
Oracle 테이블 (src/main/resources/db/oracle_board.sql 참고)
CREATE TABLE board (
    id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title      VARCHAR2(200) NOT NULL,
    writer     VARCHAR2(50)  NOT NULL,
    content    CLOB,
    view_count NUMBER        DEFAULT 0,
    created_at TIMESTAMP     DEFAULT SYSTIMESTAMP
);
*/
@Data
public class Board {
	private Long id;
	private String title;
	private String writer;   // 화면에 보이는 작성자 이름 (사용자가 입력)
	private String owner;    // 실제 작성 계정 username (수정/삭제 권한 판별용)
	private String content;
	private Integer viewCount;       // DB: view_count (map-underscore-to-camel-case)
	private LocalDateTime createdAt; // DB: created_at → JSON "2026-07-20T16:30:00"
}
