package kr.or.kosa.domain;

import lombok.Data;

/*
create table user2(
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL 
);


select * from user2;
  
  
CREATE TABLE user2 (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) UNIQUE NOT NULL,
    password VARCHAR2(255) NOT NULL,
    role VARCHAR2(20) NOT NULL
);  
  
 */
@Data
public class User {
   private long id;
   private String username;
   private String password;
   private String name;    // 사용자 이름 (프론트 Header 에 "OOO님" 으로 표시)
   private String role;
}
